version: '2.0'
services:
  postgres:
    image: postgres
    restart: always
    container_name: czech
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: czech
      POSTGRES_USER: czech
      POSTGRES_PASSWORD: czech
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  postgres:
